const START_COORDINATE = {
  lat: 35.66023,
  lng: 139.73007,
};
const ADVERTISEMENT_COUNT = 10;
const ALERT_SHOW_TIME = 700;
const TIMEOUT_DELAY = 500;

export {START_COORDINATE, ADVERTISEMENT_COUNT, ALERT_SHOW_TIME, TIMEOUT_DELAY};
