const START_COORDINATE = {
  lat: 35.66023,
  lng: 139.73007,
};
const SIMILAR_ADVERTISEMENT_COUNT = 10;
const ALERT_SHOW_TIME = 700;

export {START_COORDINATE, SIMILAR_ADVERTISEMENT_COUNT, ALERT_SHOW_TIME};
